// console.log("hello world");

// alert("apna colllage");

// console.dir(document.body.childNodes);

// console.log(document.body);

// let heading =document.getElementById("heading");
// console.dir(heading);

// let headings = document.getElementsByClassName("heading-class");
// console.dir(headings);
// console.log(headings); 



// let firstele = document.querySelector("p");
// console.dir(firstele);

// let allelem = document.querySelectorAll("p");
// console.log(allelem);



// let div = document.querySelector("div");
// console.log(div);


// let id = div.getAttribute("id");
// console.log(id);

// let name= div.getAttribute("name");
// console.log(name);






// let div = document.querySelector("div");
// div.style.backgroundColor = "green";
// div.style.backgroundColor  ="purple";
// div.style.visibility  ="hidden";
// div.style.fontsize  ="26px";

// div.innertext = "hello";




// let newBtn = document.createElement("button");
// newBtn.innerText ="click me!";
// console.log(newBtn);





// let div = document.querySelector("div");
// div.append(newBtnn);

// let div = document.querySelector("div");
// div.prepend(newBtn);


let newheading = document.createElement("h1");
newheading.innerHTML ="<i>hi, I am new!</i>";

document.querySelector("body").append(newheading);


let para = document.querySelector("p");
para.remove(); 


newheading.remove();




